### ISSUE TITLE
Exception: Lookbook::LookbookError: uninitialized constant

### ISSUE THREAD

**Issue by raivil** [ViewComponent/lookbook#251]
### Describe the bug

After upgrading from 1.3.4 to 1.4.0, the initialization process (rails, puma,sidekiq, console, etc) started warning about `uninitialized constant` on an existing view component.
Additionally, the lookbook opena simple page without the components (see screenshot) and hangs the browser until it give up on loading the page.
The websocket connection stays as `pending`

Update: On version `1.3.4`, the same error happens when accessing the lookbook, however the UI loads and the components can be selected/viewed.

### To Reproduce

Boot any rails server or console.

```
web      | 2022-11-30 08:06:21.384893 E [80279:8220 preview_collection.rb:25] Rails -- Exception: Lookbook::LookbookError: uninitialized constant Shared::FlashMessages::Component::Preview
web      | 
web      |       Object.const_get(camel_cased_word)
web      |             ^^^^^^^^^^
web      | Did you mean?  PreviewHelper
web      | 
```

### Expected behavior

No error during initialization.
Lookbook is accessible.

### Screenshots
![image](https://user-images.githubusercontent.com/2623565/204782811-f6a77850-f797-496f-b30c-917b68313d7e.png)

### Version numbers 

Please complete the following information:

* Lookbook:  `lookbook (~> 1.4.0)`
* ViewComponent: 
```
   gem "primer_view_components", "~> 0.0.112"
  gem "view_component", "~> 2.78.0"
  gem "view_component-contrib", "~> 0.1.1"
```
* Rails: `Rails 7.0.4`
* Ruby: `ruby 3.1.2p20`

### Screenshots
![image](https://user-images.githubusercontent.com/2623565/204782670-237cee28-4bcf-484a-a917-399e67f8c243.png)

### Additional context
Puma logs:

```
web      | => Booting Puma
web      | => Rails 7.0.4 application starting in development 
web      | => Run `bin/rails server --help` for more startup options
web      | 2022-11-30 08:12:27.422412 E [82303:8220 preview_collection.rb:25] Rails -- Exception: Lookbook::LookbookError: uninitialized constant Shared::FlashMessages::Component::Preview
web      | 
web      |       Object.const_get(camel_cased_word)
web      |             ^^^^^^^^^^
web      | Did you mean?  PreviewHelper
web      | 
web      | 2022-11-30 08:12:28.355200 I [82303:8220] Rails -- Initializing websocket
web      | 2022-11-30 08:12:28.408286 D [82303:8220] Rails -- Starting listeners
web      | Puma starting in single mode...
web      | * Puma version: 6.0.0 (ruby 3.1.2-p20) ("Sunflower")
web      | *  Min threads: 5
web      | *  Max threads: 5
web      | *  Environment: development
web      | *          PID: 82303
web      | * Listening on http://127.0.0.1:3000
web      | * Listening on http://[::1]:3000
web      | Use Ctrl-C to stop
web      | 2022-11-30 08:14:13.678754 I [82303:puma srv tp 005] Rails -- Started GET "/lookbook" for 127.0.0.1 at 2022-11-30 08:14:13 -0300
web      | 2022-11-30 08:14:13.749699 I [82303:puma srv tp 005] Rails -- Processing by Lookbook::ApplicationController#index as HTML
web      | 2022-11-30 08:14:13.983822 D [82303:puma srv tp 005] Rails -- [IdentityCache] (cache_backend) cache hit for IDC:8:attr:Account:id:slug:17521394893211792413
web      | 2022-11-30 08:14:13.984118 D [82303:puma srv tp 005] ActionView::Base --   Rendering layout /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.4.1/app/views/layouts/lookbook/application.html.erb
web      | 2022-11-30 08:14:13.984151 D [82303:puma srv tp 005] ActionView::Base --   Rendering /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.4.1/app/views/lookbook/index.html.erb within layouts/lookbook/application
web      | 2022-11-30 08:14:13.984227 I [82303:puma srv tp 005] ActionView::Base --   Rendered /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.4.1/app/views/lookbook/index.html.erb within layouts/lookbook/application (Duration: 0.1ms | Allocations: 35)
web      | 2022-11-30 08:14:14.721928 D [82303:puma srv tp 005] ActionView::Base --   Rendering /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.4.1/app/views/layouts/lookbook/shell.html.erb
web      | 2022-11-30 08:14:14.735058 D [82303:puma srv tp 005] ActionView::Base --   Rendering /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.4.1/app/views/layouts/lookbook/skeleton.html.erb
web      | 2022-11-30 08:14:14.736116 I [82303:puma srv tp 005] ActionView::Base --   Rendered /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.4.1/app/views/layouts/lookbook/skeleton.html.erb (Duration: 1.0ms | Allocations: 240)
web      | 2022-11-30 08:14:14.736649 I [82303:puma srv tp 005] ActionView::Base --   Rendered /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.4.1/app/views/layouts/lookbook/shell.html.erb (Duration: 14.7ms | Allocations: 18750)
web      | 2022-11-30 08:14:14.737030 I [82303:puma srv tp 005] ActionView::Base --   Rendered layout /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.4.1/app/views/layouts/lookbook/application.html.erb (Duration: 752.9ms | Allocations: 2138264)
web      | 2022-11-30 08:14:14.737213 I [82303:puma srv tp 005] Rails -- Completed 200 OK in 987ms (Views: 753.2ms | ActiveRecord: 0.0ms | Allocations: 2142059)
web      | 
web      | 
web      | 2022-11-30 08:14:14.873199 I [82303:puma srv tp 005] Rails -- Started GET "/lookbook-assets/css/lookbook.css?v=1.4.1" for 127.0.0.1 at 2022-11-30 08:14:14 -0300
web      | 2022-11-30 08:14:14.894188 I [82303:puma srv tp 002] Rails -- Started GET "/lookbook-assets/css/themes/indigo.css?v=1.4.1" for 127.0.0.1 at 2022-11-30 08:14:14 -0300
web      | 2022-11-30 08:14:15.016616 I [82303:puma srv tp 005] Rails -- Started GET "/lookbook-assets/js/lookbook.js?v=1.4.1" for 127.0.0.1 at 2022-11-30 08:14:15 -0300
web      | 2022-11-30 08:14:15.105511 I [82303:puma srv tp 002] Rails -- Started GET "/lookbook-assets/css/lookbook.css.map" for 127.0.0.1 at 2022-11-30 08:14:15 -0300
web      | 2022-11-30 08:14:15.130154 I [82303:puma srv tp 003] Rails -- Started GET "/lookbook-assets/css/themes/indigo.css.map" for 127.0.0.1 at 2022-11-30 08:14:15 -0300
web      | 2022-11-30 08:14:15.248901 I [82303:puma srv tp 005] Rails -- Started GET "/lookbook-assets/js/lookbook.js.map" for 127.0.0.1 at 2022-11-30 08:14:15 -0300
web      | 2022-11-30 08:14:15.294233 I [82303:puma srv tp 004] Rails -- Started GET "/lookbook/cable?uid=1669806855321" for 127.0.0.1 at 2022-11-30 08:14:15 -0300
web      | 2022-11-30 08:14:15.348597 I [82303:puma srv tp 001] Rails -- Started GET "/lookbook-assets/feather-sprite.svg" for 127.0.0.1 at 2022-11-30 08:14:15 -0300
web      | 2022-11-30 08:14:15.521296 I [82303:puma srv tp 004] Rails -- Started GET "/lookbook/cable/?uid=1669806855321" [WebSocket] for 127.0.0.1 at 2022-11-30 08:14:15 -0300
web      | 2022-11-30 08:14:15.521352 I [82303:puma srv tp 004] Rails -- Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
web      | 2022-11-30 08:14:15.542478 I [82303:ActionCable-worker-1] [1669806855321] Rails -- connected to Lookbook
web      | 2022-11-30 08:14:15.542549 I [82303:ActionCable-worker-1] [1669806855321] Rails -- Registered connection (1669806855321)
```

Full stack error on version `1.3.4`
```
web      | 2022-11-30 08:21:31.946542 I [84660:puma srv tp 002] Rails -- Processing by Lookbook::ApplicationController#index as HTML
web      | 2022-11-30 08:21:32.691072 E [84660:puma srv tp 002 preview.rb:155] Rails -- Exception: Lookbook::Error: Uninitialized constant Shared::FlashMessages::Component::Preview
web      | 
web      |       Object.const_get(camel_cased_word)
web      |             ^^^^^^^^^^
web      | Did you mean?  PreviewHelper
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `const_get'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `constantize'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.3.4/lib/lookbook/preview.rb:152:in `block in all'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.3.4/lib/lookbook/preview.rb:151:in `map'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.3.4/lib/lookbook/preview.rb:151:in `all'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/lookbook-1.3.4/app/controllers/lookbook/application_controller.rb:34:in `assign_collections'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:400:in `block in make_lambda'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:200:in `block in halting'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:595:in `block in invoke_before'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:595:in `each'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:595:in `invoke_before'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:116:in `block in run_callbacks'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ahoy_matey-4.1.0/lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actiontext-7.0.4/lib/action_text/rendering.rb:20:in `with_renderer'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actiontext-7.0.4/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:233:in `process_action'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `block in instrument'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `instrument'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:151:in `process'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionview-7.0.4/lib/action_view/rendering.rb:39:in `process'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal.rb:188:in `dispatch'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal.rb:251:in `dispatch'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `each'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `serve'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:852:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:530:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/railtie.rb:226:in `public_send'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/railtie.rb:226:in `method_missing'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb:48:in `serve'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `each'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `serve'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:852:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/static.rb:23:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-attack-6.6.1/lib/rack/attack.rb:103:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/static.rb:161:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/conditional_get.rb:27:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/cookies.rb:696:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/migration.rb:603:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:99:in `run_callbacks'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:132:in `call_app'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:28:in `block in call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `catch'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/rack/logger.rb:40:in `call_app'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/rack/logger.rb:25:in `block in call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/semantic_logger-4.12.0/lib/semantic_logger/base.rb:190:in `block in tagged'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/semantic_logger-4.12.0/lib/semantic_logger/semantic_logger.rb:347:in `tagged'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/semantic_logger-4.12.0/lib/semantic_logger/base.rb:202:in `tagged'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/rack/logger.rb:25:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ahoy_matey-4.1.0/lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/request_id.rb:26:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-timeout-0.6.3/lib/rack/timeout/core.rb:148:in `block in call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-timeout-0.6.3/lib/rack/timeout/support/timeout.rb:19:in `timeout'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-timeout-0.6.3/lib/rack/timeout/core.rb:147:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/static.rb:23:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/agent.rb:433:in `with_rack_env'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/rack/error_notifier.rb:30:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/rack/user_feedback.rb:31:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/rack/user_informer.rb:21:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiler.rb:393:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/shakapacker-6.5.4/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-proxy-0.7.4/lib/rack/proxy.rb:78:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:530:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:268:in `call'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/request.rb:89:in `block in handle_request'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/thread_pool.rb:343:in `with_force_shutdown'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/request.rb:88:in `handle_request'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/server.rb:430:in `process_client'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/server.rb:233:in `block in run'
web      | /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/thread_pool.rb:150:in `block in spawn_thread'
```

**Comment by HectorMF** [comment]
Hey I've been having this issue for the past couple days, but i don't have any errors in my logs. 

Try removing your application_view_component_preview.rb out of the components folder and see if that does anything. 

For me it is definitely a conflict between view_component-contrib and lookbook. Something has changed between 1.3.4 and 1.4.0 that changes how lookbook is finding or rendering the "abstract" preview.

The default view_component-contrib structure is as follows. 

```txt
components/
    application_view_component.rb
    application_view_component_preview.rb

    example/
        component.html
        component.rb
        preview.rb
        index.css
        index.js
```
and the preview path is config.view_component.preview_paths << Rails.root.join("app", "frontend", "components").

Previews are compiled from all files ending in "_preview.rb" in the components folder. This would include the application_view_component_preview.rb, but it's removed from the preview list by view_component-contrib.  If I move this file from the components folder Lookbook works for me again.  Still trying to figure out why this is happening.

**Comment by allmarkedup** [comment]
Hey @raivil & @HectorMF - thanks for the bug report and all the detailed info.

I've not had a chance to dig in too deeply yet but I have spotted one place where some of the recent changes to Lookbook might not be playing very nicely together with `view_component-contrib`.

I've pushed a small fix up in the `view-component-contrib-interop` branch - do you think you could give it a quick test for me and see if it resolved the problems you are seeing?

```ruby
gem "lookbook", git: "git://github.com/ViewComponent/lookbook.git", branch: "view-component-contrib-interop"
```

There may well be other incompatibilities that I need to look at but it would be good to see if I can deal with the low hanging fruit first.

Thanks for bringing this to my attention and hopefully we can get it resolved quickly :-)

**Comment by HectorMF** [comment]
@allmarkedup that's fast, your fix solves the abstract preview issue for me. 

I don't know how often people subclass a component, but I wrote a quick two component test without view_component-contrib that is related to this issue. It also hangs until out of memory.

Lookbook works just fine if the preview files are placed in "test/components/previews", however it will not work if the preview_path is anywhere else. 

https://github.com/HectorMF/lookbook_inheritance_test

switching the commented lines in application.rb will make it work or not.

```
config.view_component.preview_paths << Rails.root.join("app", "components", "previews")
#config.view_component.preview_paths << Rails.root.join("test", "components", "previews")
```

**Comment by allmarkedup** [comment]
@HectorMF great, glad to know the abstract preview fix worked, and very much appreciate you taking the time to put the test app together - really helpful. I've just pulled it down and can see the issue so will try to figure out what is going on there. Inheritance should definitely work so there is something odd going on!

**Comment by raivil** [comment]
> application_view_component_preview

The fix doesn't seem to work here.
Got the same issues (exception message and lookbook not loading).

I've also tried moving the `application_view_component_preview.rb` out of the components folder or renaming it so it doesn't end in "preview.rb" without luck.


This is a snipped of the config that I forgot to include on the first post:
```
(from config/environments/development.rb)

  primer_gem_dir = Gem::Specification.find_by_name("primer_view_components").gem_dir
  config.view_component.show_previews_source = true
  config.view_component.preview_paths << Rails.root.join("app/frontend/components")
  config.view_component.preview_paths << Rails.root.join("#{primer_gem_dir}/test/previews")

  config.lookbook.listen_paths << Rails.root.join("#{primer_gem_dir}/app/components")
  config.lookbook.preview_paths << Rails.root.join("app/frontend/components")
```

Is there anything else I can provide to help track down this issue?

**Comment by allmarkedup** [comment]
@raivil ok thanks, I've just pushed another change to the `view-component-contrib-interop` branch - could you see if that makes any difference to you?

**Comment by allmarkedup** [comment]
@HectorMF just testing your test app above and I think this latest fix should also fix the problem there 👍

**Comment by raivil** [comment]
@allmarkedup I can access the lookbook and the components preview with the new update.
I still see the "uninitialized constant" error during rails boot.

**Comment by allmarkedup** [comment]
@raivil so is the error actually preventing anything from working that you can tell? I think it may be to do with Rails reloading classes in development but I've not yet been able to replicate it on my setup.

If it's not causing any issues anymore it might just be that Lookbook is parsing those class files before they are actually loaded (which isn't necessarily a problem in itself if things are working as expected, although obviously it would be good to avoid all the error messages).

**Comment by raivil** [comment]
@allmarkedup I just noticed that some components are not working (the preview). It shows a "not found".
I've created a test component and this is what I got. It lists the previews but I get errors to access them.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/2623565/205339609-ec69f583-1818-45cf-afe0-a67f4752f7f5.png">

**Comment by allmarkedup** [comment]
@HectorMF @raivil I've just released v1.4.2 that contains the `view_component-contrib` compatibility fixes - let me know how you get on with it when you have a chance to update if you can :-)

@raivil I realise that you are still experiencing some additional issues but I wanted to get those fixes out while I try to track down the cause of your problems as I've not yet been able to recreate them at my end yet. I'm going to have another look at it later and will let you know if I figure anything out.

**Comment by tellodaniel** [comment]
We are using:

```
gem 'view_component', '>= 3.0.0.rc2'
gem 'lookbook', '>= 2.0.0.beta.3'
```

with this configs:

```
    # Lookbook configs
    config.lookbook.ui_theme = 'green'
    config.view_component.preview_paths << "#{Rails.root}/spec/components/previews"
    config.lookbook.page_paths << "#{Rails.root}/spec/components/docs"
    config.view_component.default_preview_layout = 'component_preview'
    config.lookbook.preview_params_options_eval = true
    config.lookbook.sort_examples = true
    config.lookbook.preview_display_options = {
      theme: %w(light dark),
      lang: [
        %w(English en),
        %w(Spanish es),
      ],
    }
```

And we are facing the same problem in our staging and production environment. Is this fix merged in V2? @allmarkedup

**Comment by tellodaniel** [comment]
@allmarkedup Our problem was our autoloading paths we added this to our `application.rb`. Our component definition looked more or less like this:

```
    config.autoload_paths << config.root.join('spec', 'components', 'previews')
    config.eager_load_paths << config.root.join('spec', 'components', 'previews')
```

**Comment by allmarkedup** [comment]
hey @tellodaniel, reading your message I'm not quite sure if you mean that you have fixed your issue (with the addition of the autoload paths) or not? Is it all okay now?

**Comment by allmarkedup** [comment]
@tellodaniel fantastic, glad to hear it! :-)
